# Use root/example as user/password credentials
# docker-compose up
version: '3.1'

services:
    php72_apache:
      build:
        context: ./.docker
      volumes:
        - .apache/:/etc/apache2/v-host/
        - .:/var/www
      ports:
        - 8010:80
